/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:aee7b253-17cc-46e8-a8c4-5639a74cf3a3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PbdoXH2FU",
    "aws_user_pools_web_client_id": "2see6lqum408pr8j41sjr0pr34",
    "oauth": {
        "domain": "platform-576727010490.auth.us-east-1.amazoncognito.com",
        // "scope": [
        //     "phone",
        //     "email",
        //     "openid",
        //     "profile",
        //     "aws.cognito.signin.user.admin"
        // ],
        "redirectSignIn": "https://wisbe.com.br/",
        "redirectSignOut": "https://wisbe.com.br/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
